# LAB | Intro to Machine Learning

**Load the data**

In this challenge, we will be working with Spaceship Titanic data.  

 The data can be found here:  Es el archivo donde están los valores reales:

filas

columnas

números

textos

registros

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv

Metadata

No son los datos.
Es descripción de los datos.

Ejemplos de metadata:

qué significa cada columna

tipo de dato (int, float, string)

unidades (kg, €)

fecha de creación del dataset

quién lo generó

cuántas filas tiene

si hay valores nulos

diccionario de datos

👉 La metadata describe al CSV, pero no es el CSV.

https://github.com/data-bootcamp-v4/data/blob/main/spaceship_titanic.md

Esto son los metadatos

In [ ]:
# Id: Unique identifier for each property.
# 1- PassengerId - A unique Id for each passenger. 
# Each Id takes the form gggg_pp where gggg indicates a group the passenger is travelling with and pp is their number within the group. 
# People in a group are often family members, but not always.
# ----------------------
# 2- HomePlanet - The planet the passenger departed from, typically their planet of permanent residence.
# ----------------------
# 3- CryoSleep - Indicates whether the passenger elected to be put into suspended animation for the duration of the voyage.
# Passengers in cryosleep are confined to their cabins.
# ----------------------
# 4- Cabin - The cabin number where the passenger is staying. 
# Takes the form 
#     deck/num/side, 
#     deck = cubierta barco 
#     num = numero_cabina
#     where side can be either P for Port or S for Starboard. (por babor o por estribor)
# ----------------------
# 5- Destination - The planet the passenger will be debarking to.
# ----------------------
# 6- Age - The age of the passenger.
# ----------------------
# 7- VIP - Whether the passenger has paid for special VIP service during the voyage. RoomService, FoodCourt, ShoppingMall, Spa, 
# ----------------------
# 12- VRDeck - Amount the passenger has billed at each of the Spaceship Titanic's many luxury amenities.
# ----------------------
# 13- Name - The first and last names of the passenger.
# ----------------------
# 14- Transported - Whether the passenger was transported to another dimension.
#  This is the target, the column you are trying to predict.

In [43]:
#import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split #pip install scikit-learn si no lo tenemos instalado

In [44]:
spaceship = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv")
spaceship.head(10)

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
5,0005_01,Earth,False,F/0/P,PSO J318.5-22,44.0,False,0.0,483.0,0.0,291.0,0.0,Sandie Hinetthews,True
6,0006_01,Earth,False,F/2/S,TRAPPIST-1e,26.0,False,42.0,1539.0,3.0,0.0,0.0,Billex Jacostaffey,True
7,0006_02,Earth,True,G/0/S,TRAPPIST-1e,28.0,False,0.0,0.0,0.0,0.0,NaN,Candra Jacostaffey,True
8,0007_01,Earth,False,F/3/S,TRAPPIST-1e,35.0,False,0.0,785.0,17.0,216.0,0.0,Andona Beston,True
9,0008_01,Europa,True,B/1/P,55 Cancri e,14.0,False,0.0,0.0,0.0,0.0,0.0,Erraiam Flatic,True

**Check the shape of your data**

In [45]:
spaceship.shape

(8693, 14)

**Check for data types**

In [46]:
spaceship.dtypes

PassengerId         str
HomePlanet          str
CryoSleep        object
Cabin               str
Destination         str
Age             float64
VIP              object
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Name                str
Transported        bool
dtype: object

**Check for missing values**

In [47]:
spaceship.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

There are multiple strategies to handle missing data

- Removing all rows or all columns containing missing data.
- Filling all missing values with a value (mean in continouos or mode in categorical for example).
- Filling all missing values with an algorithm.

For this exercise, because we have such low amount of null values, we will drop rows containing any missing value.

In [48]:
spaceship = spaceship.dropna()
spaceship.shape

(6606, 14)

**KNN**

K Nearest Neighbors is a distance based algorithm, and requeries all **input data to be numerical.**

Let's only select numerical columns as our features.

In [49]:
features  = spaceship.select_dtypes(include=["int64", "float64"])  # Variables de entrada al modelo

And also lets define our target.

In [50]:
target = spaceship["Transported"]

**Train Test Split**

Now that we have split the data into **features** and **target** variables and imported the **train_test_split** function, split X and y into X_train, X_test, y_train, and y_test. 80% of the data should be in the training set and 20% in the test set.

In [51]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.20, random_state=0)

| Variable | Qué contiene | Para qué sirve |
| --- | --- | --- |
| **X_train** | Features (80%) | Entrenar el modelo |
| **X_test** | Features (20%) | Evaluar el modelo |
| **y_train** | Target (80%) | Entrenar |
| **y_test** | Target (20%) | Evaluar |

In [52]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (5284, 6)
X_test: (1322, 6)
y_train: (5284,)
y_test: (1322,)

In [53]:
X_train.head()

       Age  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck
3432  32.0          0.0        0.0           0.0     0.0     0.0
7312   4.0          0.0        0.0           0.0     0.0     0.0
2042  30.0          0.0      236.0           0.0  1149.0     0.0
4999  17.0         13.0        0.0         565.0   367.0     1.0
5755  26.0          0.0        0.0           0.0     0.0     0.0

In [54]:
X_test.head()

       Age  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck
2453  50.0          0.0        0.0           0.0     0.0     0.0
1334  18.0          0.0        0.0           0.0     0.0     0.0
8272  15.0          0.0        0.0           0.0     0.0     0.0
5090  52.0          0.0        0.0           0.0     0.0     0.0
4357  62.0          0.0     1633.0           0.0  1742.0     0.0

In [55]:
y_train.head()

3432    False
7312     True
2042    False
4999    False
5755     True
Name: Transported, dtype: bool

In [56]:
y_test.head()

2453     True
1334    False
8272     True
5090    False
4357     True
Name: Transported, dtype: bool

**Model Selection**

In this exercise we will be using **KNN** as our predictive model.

You need to choose between **Classificator** or **Regressor**.  
Take into consideration target variable to decide.

Initialize a KNN instance without setting any hyperparameter.

In [57]:
from sklearn.neighbors import KNeighborsClassifier

Fit the model to your data.

In [58]:
knn = KNeighborsClassifier(n_neighbors=3)

Evaluate your model.

In [59]:
knn

KNeighborsClassifier(n_neighbors=3)

| Parámetro | Valor | Qué significa | Impacto en el modelo |
| --- | --- | --- | --- |
| **n_neighbors** | 3 | Número de vecinos que se usan para clasificar | Muy alto |
| **weights** | 'uniform' | Todos los vecinos pesan igual | Medio |

In [60]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

Hago las predicciones

| Variable | Qué contiene | Para qué sirve |
| --- | --- | --- |
| **X_train** | Features (80%) | Entrenar el modelo |
| **X_test** | Features (20%) | Evaluar el modelo |
| **y_train** | Target (80%) | Entrenar |
| **y_test** | Target (20%) | Evaluar |

In [ ]:
pred = knn.predict(X_test) # esta es la prediccion para usar luego
pred

array([ True,  True,  True, ...,  True,  True, False], shape=(1322,))

Vamos a sacar los valores reales que deberia dar para comparar

In [62]:
y_test.values

array([ True, False,  True, ...,  True,  True,  True], shape=(1322,))


Para poder evaluar nuestro modelo utilizaremos el método "score" que nos dará precisión

In [71]:
knn.score(X_test, y_test) # accuracy

0.735249621785174

| Variable | Qué contiene | Para qué sirve |
| --- | --- | --- |
| **X_train** | Features (80%) | Entrenar el modelo |
| **X_test** | Features (20%) | Evaluar el modelo |
| **y_train** | Target (80%) | Entrenar |
| **y_test** | Target (20%) | Evaluar |

Accuracy es siempre global.
Precision, recall y F1 son por clase primero, y globales solo después de promediarlas.

Ahora comparamos la prediccion con el resultado segun diferentes funciones

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
# accuracy
print(accuracy_score(y_test, pred)) #le paso las predicciones manualmente. Sale lo mismo que con knn.score(X_test, y_test)

# precision
print(precision_score(y_test, pred, average='macro'))

# recall
print(recall_score(y_test, pred, average='macro'))

# F1-score
print(f1_score(y_test, pred, average='macro'))

0.735249621785174
0.7354242012656981
0.735249621785174
0.7352005310868968

Vamos a ver que dice la confusion matrix

In [76]:
# confusion matrix

##[[TN FP]
 ##[FN TP]]

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[477, 184],
       [166, 495]])

In [ ]:
# scikit‑learn ordena las clases en orden alfabético / lógico antes de construir la matriz de confusión.
# por tanto False = 0 y true = 1  y sale asi la matriz 
#  [[TN, FP],     -----------   
#  [FN, TP]]

# TN = 477 TN (True Negatives)  : aciertos en NO transportados
# FP = 184 FP (False Positives) : dice transportado pero no lo es
# FN = 166 FN (False Negatives) : dice no transportado pero sí lo es
# TP = 495 TP (True Positives) : aciertos en transportados

In [ ]:
# Pedimos a scikit‑learn que te imprima un informe completo de cómo ha clasificado tu modelo, mucho más detallado que accuracy.

# La columna support solo cuenta pasajeros reales en cada tipo

In [77]:
from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

       False       0.74      0.72      0.73       661
        True       0.73      0.75      0.74       661

    accuracy                           0.74      1322
   macro avg       0.74      0.74      0.74      1322
weighted avg       0.74      0.74      0.74      1322

CONCLUSION:
La confusion matriz refleja 
acerto en 477 no transportados y fallo en 184
acerto en 495 transportados y fallo en 166

El modelo con datos esta balanceado con 661 para cada caso por lo que los resultados de accuracy son fiables.

El 73,5 % indica un alto aprendizaje , pero para estudios como el que hemos hecho con vidas humanas donde los errores salen muy caros
no es un estudio muy aconsejable.